version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "Clone"
  - "Build"
  - "Unit Test"
  - "Integration Test"
  - "Feature Test"
  - "Performance Test"

steps:
  clone:
    title: "Cloning repository"
    stage: "clone"
    type: "git-clone"
    repo: "vitormcruz/payroll_groovy"
    revision: "${{CF_BRANCH}}"
    git: "github"

  build:
    title: "Building Payroll"
    stage: "Build"
    type: "freestyle"
    image: "maven:3.6.3-jdk-11-slim"
    working_directory: "${{clone}}"
    commands:
      - mvn package -DskipTests



#steps:
#
#  - name: Build
#    image: maven:3.6.3-jdk-11-slim
#    commands:
#      - mvn test-compile
#      -
#  - name: Unit Test
#    image: maven:3.6.3-jdk-11-slim
#    commands:
#      - mvn test -Dtest=*UnitTest
#    depends_on: [ Build ]
#
#  - name: Integration Test
#    image: maven:3.6.3-jdk-11-slim
#    commands:
#      - mvn test -Dtest=*IntTest
#    depends_on: [ Build ]
#
#  - name: Feature Test
#    image: maven:3.6.3-jdk-11-slim
#    commands:
#      - mvn test -Dtest=*FeatureTest
#    depends_on: [ Build ]
#
#  - name: Performance Test
#    image: maven:3.6.3-jdk-11-slim
#    commands:
#      - mvn test -Dtest=*PerformanceTest
#    depends_on: [ Build ]