name: CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  
  Run Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
    
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build
        env: 
          TEST_MACHINE_PERFORMANCE_DEGRADATION_FACTOR: 4
          
        run: mvn package -DskipTest -Pproduction
          
  Build:
    runs-on: ubuntu-latest
    needs: [Run Tests]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
    
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          
      - name: Build
        run: mvn package -DskipTest -Pproduction

